import './globals.css'
import type { Metadata } from 'next'
import Head from 'next/head'
import Layout from '@/components/layouts/BaseLayout'
import { Component } from 'react'


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja-JP">
      <head>
          <meta charSet="utf-8" />
          <meta name="format-detection" content="telephone=no" />
          <link rel="shortcut icon" href={'/favicon.ico'} />
          <link rel="apple-touch-icon" href={'/logo.png'} />
      </head>
      <body>
        <Layout>
              <Head>
                  <title />
                  <meta name='viewport' content='width=device-width, initial-scale=1' />
              </Head>
              {children}
          </Layout>
      </body>
  </html>    
  )
}
